# Generated by Django 4.0 on 2026-02-12 02:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=20)),
                ('rank', models.CharField(choices=[('administer', 'administer'), ('moderator', 'moderator'), ('staff', 'staff'), ('visitor', 'visitor')], default='visitor', max_length=20, verbose_name='ランク')),
                ('member_num', models.BigIntegerField(default=main.models.random_num, verbose_name='会員番号')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('is_password_encrypted', models.BooleanField(default=False, verbose_name='パスワード暗号化フラグ')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='プロフィール写真')),
                ('remarks', models.TextField(blank=True, max_length=500, verbose_name='備考・自己紹介')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', main.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(default='com', max_length=20, verbose_name='会社コード')),
                ('address', models.CharField(default='gmail.com', max_length=20, verbose_name='アドレス')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='講座名')),
                ('courseCount', models.IntegerField(default=0, verbose_name='講座数')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効かどうか')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='検定名')),
                ('exams_file', models.FileField(blank=True, null=True, upload_to='exams_files/', verbose_name='教材ファイル')),
                ('description', models.TextField(blank=True, verbose_name='説明・研修テキスト')),
                ('passing_score', models.IntegerField(default=80, verbose_name='合格基準点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開状態')),
                ('exam_type', models.CharField(choices=[('mock', '仮試験'), ('main', '本試験')], default='mock', max_length=10, verbose_name='試験タイプ')),
                ('time_limit', models.PositiveIntegerField(default=30, help_text='0を入力すると無制限になります', verbose_name='制限時間（分）')),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_exams', to='main.exam', verbose_name='前提となる仮試験')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='例題文')),
                ('explanation', models.TextField(blank=True, verbose_name='解説')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='研修名')),
                ('video', models.FileField(blank=True, null=True, upload_to='training_videos/', verbose_name='研修動画')),
                ('training_file', models.FileField(blank=True, null=True, upload_to='exams_files/', verbose_name='要約元資料(PDF/画像)')),
                ('estimated_time', models.PositiveIntegerField(default=30, help_text='受講者がこの研修を終えるのにかかる目安の時間（分）です', verbose_name='推奨学習時間(分)')),
                ('content_text', models.TextField(blank=True, verbose_name='研修テキスト')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.course', verbose_name='所属コース')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingExampleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='選択肢')),
                ('is_correct', models.BooleanField(default=False, verbose_name='これが正解か')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='main.trainingexample')),
            ],
        ),
        migrations.AddField(
            model_name='trainingexample',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='main.trainingmodule', verbose_name='対象研修'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='問題文')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.exam')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開状態')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('is_important', models.BooleanField(default=False, verbose_name='重要')),
                ('category', models.CharField(choices=[('news', '一般'), ('training', '復習通知'), ('urgent', '重要告知')], default='news', max_length=20, verbose_name='ジャンル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user', verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'お知らせ',
            },
        ),
        migrations.CreateModel(
            name='Mylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mylists', to='main.course')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mylists', to='main.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylist_items', to='main.user')),
            ],
            options={
                'verbose_name': 'マイリスト',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='獲得スコア')),
                ('is_passed', models.BooleanField(verbose_name='合否')),
                ('taken_at', models.DateTimeField(auto_now_add=True, verbose_name='受験日時')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exam', verbose_name='受験した検定')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='受験者')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='選択肢の内容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='これが正解か')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='main.question')),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='バッジ名')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/', verbose_name='バッジ画像')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='main.exam')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='mylist',
            field=models.ManyToManyField(blank=True, related_name='mylist_users', through='main.Mylist', to='main.Course'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position', models.FloatField(default=0.0, verbose_name='再生位置(秒)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了フラグ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trainingmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='UserExamStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_passed', models.BooleanField(default=False, verbose_name='合格したか')),
                ('passed_at', models.DateTimeField(blank=True, null=True, verbose_name='合格日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exam', verbose_name='検定')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='ユーザー')),
            ],
            options={
                'unique_together': {('user', 'exam')},
            },
        ),
        migrations.AddConstraint(
            model_name='mylist',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('user', 'course'), name='unique_user_course_mylist'),
        ),
        migrations.AddConstraint(
            model_name='mylist',
            constraint=models.UniqueConstraint(condition=models.Q(('news__isnull', False)), fields=('user', 'news'), name='unique_user_news_mylist'),
        ),
    ]
