# Generated by Django 4.0 on 2026-01-21 01:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rank', models.CharField(choices=[('administer', '管理者'), ('moderator', 'モデレーター'), ('staff', '社員'), ('visitor', '訪問者')], default='visitor', max_length=20, verbose_name='ランク')),
                ('member_num', models.BigIntegerField(default=main.models.random_num, primary_key=True, serialize=False, verbose_name='会員番号')),
                ('name', models.CharField(max_length=20, verbose_name='氏名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('is_password_encrypted', models.BooleanField(default=False, verbose_name='パスワード暗号化フラグ')),
                ('username', models.CharField(max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', main.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(default='com', max_length=20, verbose_name='会社コード')),
                ('address', models.CharField(default='gmail.com', max_length=20, verbose_name='アドレス')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='科目')),
                ('courseCount', models.IntegerField(verbose_name='講座数')),
                ('is_mylist', models.BooleanField(default=False, verbose_name='マイリストに入っているか')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='検定名')),
                ('exams_file', models.FileField(blank=True, null=True, upload_to='exams_files/', verbose_name='教材ファイル')),
                ('description', models.TextField(blank=True, verbose_name='説明・研修テキスト')),
                ('passing_score', models.IntegerField(default=80, verbose_name='合格基準点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('exam_type', models.CharField(choices=[('mock', '仮試験'), ('main', '本試験')], default='mock', max_length=10, verbose_name='試験タイプ')),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_exams', to='main.exam', verbose_name='前提となる仮試験')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='お知らせ名')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='問題文')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='選択肢の内容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='これが正解か')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='main.question')),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='バッジ名')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/', verbose_name='バッジ画像')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='main.exam')),
            ],
        ),
        migrations.CreateModel(
            name='UserExamStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_passed', models.BooleanField(default=False, verbose_name='合格したか')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exam', verbose_name='検定')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='ユーザー')),
            ],
            options={
                'unique_together': {('user', 'exam')},
            },
        ),
    ]
