# Generated by Django 4.0 on 2026-01-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exams_file',
            field=models.FileField(blank=True, null=True, upload_to='exams_files/', verbose_name='教材ファイル'),
        ),
    ]
