# Generated by Django 4.0 on 2026-02-03 03:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='獲得スコア')),
                ('is_passed', models.BooleanField(verbose_name='合否')),
                ('taken_at', models.DateTimeField(auto_now_add=True, verbose_name='受験日時')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mylist',
            options={'verbose_name': 'マイリスト'},
        ),
        migrations.RemoveConstraint(
            model_name='mylist',
            name='unique_mylist',
        ),
        migrations.AddField(
            model_name='mylist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='登録日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mylist',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mylists', to='main.news'),
        ),
        migrations.AddField(
            model_name='userexamstatus',
            name='passed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='合格日時'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseCount',
            field=models.IntegerField(default=0, verbose_name='講座数'),
        ),
        migrations.AlterField(
            model_name='mylist',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mylists', to='main.course'),
        ),
        migrations.AddConstraint(
            model_name='mylist',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('user', 'course'), name='unique_user_course_mylist'),
        ),
        migrations.AddConstraint(
            model_name='mylist',
            constraint=models.UniqueConstraint(condition=models.Q(('news__isnull', False)), fields=('user', 'news'), name='unique_user_news_mylist'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exam', verbose_name='受験した検定'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='受験者'),
        ),
    ]
