# Generated by Django 4.0 on 2026-01-16 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='検定名')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='バッジ名')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/', verbose_name='バッジ画像')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='main.exam')),
            ],
        ),
    ]
