# Generated by Django 4.0 on 2026-01-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='プロフィール写真'),
        ),
        migrations.AddField(
            model_name='user',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, verbose_name='備考・自己紹介'),
        ),
    ]
