# Generated by Django 4.0 on 2026-01-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
