# Generated by Django 4.0 on 2026-01-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効フラグ'),
        ),
    ]
