# Generated by Django 4.0 on 2025-11-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('administer', '管理者'), ('moderator', 'モデレーター'), ('staff', '社員'), ('visitor', '訪問者')], default='visitor', max_length=20, verbose_name='ランク'),
        ),
    ]
