# Generated by Django 4.0 on 2026-02-02 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mylist',
            name='unique_mylist',
        ),
        migrations.AddField(
            model_name='mylist',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mylist_course_items', to='main.course'),
        ),
        migrations.AlterField(
            model_name='mylist',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mylist_news_items', to='main.news'),
        ),
        migrations.AddConstraint(
            model_name='mylist',
            constraint=models.UniqueConstraint(fields=('user', 'news'), name='unique_mylist_news'),
        ),
        migrations.AddConstraint(
            model_name='mylist',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_mylist_course'),
        ),
    ]
