# Generated by Django 4.0 on 2026-01-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, help_text='0を入力すると無制限になります', verbose_name='制限時間（分）'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=200, verbose_name='検定名'),
        ),
    ]
