# Generated by Django 4.0 on 2026-01-29 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exam_time_limit_alter_exam_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='mylist',
            field=models.ManyToManyField(blank=True, related_name='mylist_users', through='main.Mylist', to='main.News'),
        ),
        migrations.AddField(
            model_name='mylist',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylist_items', to='main.news'),
        ),
        migrations.AddField(
            model_name='mylist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylist_items', to='main.user'),
        ),
        migrations.AddConstraint(
            model_name='mylist',
            constraint=models.UniqueConstraint(fields=('user', 'news'), name='unique_mylist'),
        ),
    ]
