# Generated by Django 4.0 on 2026-01-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_avatar_user_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('administer', 'administer'), ('moderator', 'moderator'), ('staff', 'staff'), ('visitor', 'visitor')], default='visitor', max_length=20, verbose_name='ランク'),
        ),
    ]
