# Generated by Django 4.0 on 2026-01-23 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_avatar_user_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='投稿日'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('administer', 'administer'), ('moderator', 'moderator'), ('staff', 'staff'), ('visitor', 'visitor')], default='visitor', max_length=20, verbose_name='ランク'),
        ),
    ]
