# Generated by Django 4.0 on 2026-01-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exam_exams_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効フラグ'),
        ),
    ]
