# Generated by Django 4.0 on 2026-01-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mylist_news_read_by_user_mylist_mylist_news_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'お知らせ'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='read_by',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('news', '一般'), ('training', '復習通知'), ('urgent', '重要告知')], default='news', max_length=20, verbose_name='ジャンル'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
    ]
