# Generated by Django 4.0 on 2026-01-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_exam_is_published_alter_user_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='is_published',
        ),
        migrations.AddField(
            model_name='exam',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='公開状態'),
        ),
    ]
