# Generated by Django 4.0 on 2026-01-20 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_exam_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('mock', '仮試験'), ('main', '本試験')], default='mock', max_length=10, verbose_name='試験タイプ'),
        ),
        migrations.AddField(
            model_name='exam',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_exams', to='main.exam', verbose_name='前提となる仮試験'),
        ),
        migrations.CreateModel(
            name='UserExamStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_passed', models.BooleanField(default=False, verbose_name='合格したか')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exam', verbose_name='検定')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='ユーザー')),
            ],
            options={
                'unique_together': {('user', 'exam')},
            },
        ),
    ]
