# Generated by Django 4.0 on 2026-01-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_exam_created_at_exam_description_exam_passing_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='お知らせ名')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
