# Generated by Django 4.0 on 2026-01-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_created_at_alter_user_rank'),
        ('main', '0004_remove_exam_is_published_exam_is_deleted_and_more'),
    ]

    operations = [
    ]
