# Generated by Django 4.0 on 2026-01-25 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20260123_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='例題文')),
                ('explanation', models.TextField(blank=True, verbose_name='解説')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='研修名')),
                ('video', models.FileField(blank=True, null=True, upload_to='training_videos/', verbose_name='研修動画')),
                ('training_file', models.FileField(blank=True, null=True, upload_to='exams_files/', verbose_name='要約元資料(PDF/画像)')),
                ('estimated_time', models.PositiveIntegerField(default=30, help_text='受講者がこの研修を終えるのにかかる目安の時間（分）です', verbose_name='推奨学習時間(分)')),
                ('content_text', models.TextField(blank=True, verbose_name='研修テキスト')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.course', verbose_name='所属コース')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingExampleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='選択肢')),
                ('is_correct', models.BooleanField(default=False, verbose_name='これが正解か')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='main.trainingexample')),
            ],
        ),
        migrations.AddField(
            model_name='trainingexample',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='main.trainingmodule', verbose_name='対象研修'),
        ),
    ]
